name: Secure Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Validate Key
      run: |
        if [ -z "${{ secrets.DEEPSEEK_API_KEY }}" ]; then
          echo "::error::API密钥未配置!"
          exit 1
        fi

    - name: Replace Key
      run: |
        sed -i "s/__DEEPSEEK_API_KEY__/${{ secrets.DEEPSEEK_API_KEY }}/g" index.html
        echo "替换后的密钥片段:"
        grep "const API_KEY = '" index.html
        
    - name: Build
      run: |
        mkdir -p ./dist
        cp index.html ./dist/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        force_orphan: true
